theme: jekyll-theme-minimal
title: (Not) Thinking about the future: Inattention and Female Labor Force Participation
description: By Ana Costa-Ramon, Ursina Schaede, Michaela Slotwinski, and Anne Brenøe
